### ISSUE TITLE
Incompatibility with Unity Collections Package (namespace conflicts)

### ISSUE THREAD

**Issue by vsonixbieber** [specklesystems/speckle-unity#109]
Combining the speckle package with the unity collections package results in compilation errors due to namespace conflicts.
![Screenshot 2024-01-22 135759](https://github.com/specklesystems/speckle-unity/assets/157376061/b9bb5a12-736f-4d2b-a446-0d8c34b5f821)
I tested this behaviour in blank projects with unity versions 2021.3.16f1 and 2022.3.1f1 (build platform windows, mac & linux).

**Comment by JR-Morgan** [comment]
The other reports of this conflict appear to be with a package called [Common.Logging](https://www.nuget.org/packages/Common.Logging)

https://github.com/MoralisWeb3/unity-web3-game-kit/issues/76
https://github.com/Nethereum/Nethereum/issues/695

This isn't a package we use, however, it looks like for us, its a conflict with [System.DoubleNumerics] (https://www.nuget.org/packages/System.DoubleNumerics) specifically this internal class:

https://github.com/Weingartner/System.Numerics.DoubleVectors/blob/master/System.DoubleNumerics/Common/System/Numerics/Hashing/HashHelpers.cs

---

Its a shame Unity refuses to fix this on their end, since it would easiest to apply the fix to `umul128`. https://issuetracker.unity3d.com/issues/namespace-umul128-error-when-multiplayer-netcode-for-gameobjects-is-installed-along-with-common-dot-logging-dot-core-library

---

There's no simple fixes we can do our end, since we depend on `System.DoubleNumerics`, right now, we don't have a work around unless we decide to fork the project.

**Comment by JR-Morgan** [comment]
See forum discussion https://speckle.community/t/unity-connector-incompatibility-with-unity-collections-package/8840

**Comment by Agoxandr** [comment]
Based on [this](https://github.com/needle-mirror/com.unity.collections) I made a [fork](https://github.com/Agoxandr/com.unity.collections). It's pretty easy to keep it in sync with upstream this way.

**Comment by JR-Morgan** [comment]
Marking as `Not Planned`.
We don't have any plans to replace `System.DoubleNumerics` any time soon. 

If there's more user demand we can re-consider this.

**Comment by Agoxandr** [comment]
With Unity 6 this has also become an issue with the [light transport](https://docs.unity3d.com/Packages/com.unity.rendering.light-transport@1.0/manual/index.html) package. This package is a dependency of the core rendering package, which is part of every unity project now.
