### ISSUE TITLE
Pushed objects very different from the received ones

### ISSUE THREAD

**Issue by psarras** [specklesystems/speckle-unity#36]
How to replicate: 
- Push a stream from Revit
- Receive it in Unity
- Push back from unity

Effect
- Lost structure
- Extremely slow to load on the online viewer (haven't managed, not enough patience 😊 )

Unity pushes a single object, losing any structure from Revit. This makes it almost impossible to read on the online viewer (which probably gives us a pick to a viewer deficiency).

From Revit:

![image](https://user-images.githubusercontent.com/3820417/129167787-21f89f0f-5441-4145-a4b0-a318a4939664.png)

From Unity (Same data)

![image](https://user-images.githubusercontent.com/3820417/129168118-be636d1f-142c-43ea-841f-06dc202f5006.png)

**Comment by haitheredavid** [comment]
@psarras thanks for pointing to this! As a general note, this connector is still in a very early stage so there is a lot of missing / broken features at the moment 😿  but never fear! Progress is being made and fixes will be had 🚀

Currently the connector does not "fully" support sending data back into speckle, the only support it has now is converting and importing some simple `base` objects into unity. Until the connector will need some more love with the object conversions in order to maintain the data being pushed back into a stream, this is the expected behavior when you push back from unity (for the moment). I'm currently pushing through some of the issues with the receiver editor logic (so much lag huh 😿), but will swing back around to this issue afterwards 🛩️
